### ISSUE TITLE
Consider deleting or making this repository private

### ISSUE THREAD

**Issue by knowledgeisland** [Balajanovski/KnowledgeIsland#1]
Hi there!

It may be for the best to make this repository private (or delete it and move to another Git host) as the project is still ongoing. Other students may be tempted to copy/emulate your code, to everyone's disadvantage.

If not now, it is important that you make this code private, or delete it, at the end of the course. Future students may find this, making it easier for them to cheat.

Thanks for your understanding, and good luck with the project!

**Comment by Balajanovski** [comment]
I have applied for a github education account to set this repository as private.
The issue should be solved soon.

**Comment by knowledgeisland** [comment]
Ok great, thanks.
